src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    private ?Agence $id_agence = null;

    #[ORM\Column(length: 200)]
    private ?string $titre = null;

    #[ORM\Column(length: 50)]
    private ?string $marque = null;

    #[ORM\Column(length: 50)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 200)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdAgence(): ?Agence
    {
        return $this->id_agence;
    }

    public function setIdAgence(?Agence $id_agence): self
    {
        $this->id_agence = $id_agence;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }
}

src/Form/VehiculeType.php
<?php

namespace App\Form;

use App\Entity\Vehicule;
use App\Entity\Agence;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;



class VehiculeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'label' => 'titre',
                'required' => false,
                "attr" => [
                    "placeholder" => "titre",
                    "class" => "form-control"
                ]
            ])
            ->add('marque', TextType::class, [
                'label' => 'marque',
                'required' => false,
                "attr" => [
                    "placeholder" => "marque",
                    "class" => "form-control"
                ]
            ])
            ->add('modele', TextType::class, [
                'label' => 'modele',
                'required' => false,
                "attr" => [
                    "placeholder" => "modele",
                    "class" => "form-control"
                ]
            ])
            ->add('description', TextareaType::class, [
                'label' => 'description',
                'required' => false,
                "attr" => [
                    "placeholder" => "description",
                    "class" => "form-control"
                ]
            ])
            ->add('photo', TextType::class, [
                "label" => "Photo",
                "required" => false,
                "attr" => [
                    "placeholder" => "photo",
                    "class" => "form-control"
                ]
            ])
            ->add('prix_journalier', NumberType::class, [
                "label" => "prix_journalier",
                "required" => false,
                "attr" => [
                    "placeholder" => "prix_journalier",
                    "class" => "form-control"
                ]
            ])
            ->add('id_agence', EntityType::class, [

                'class' => Agence::class,
                'choice_label' => 'titre',

            ])
            ->add('Ajouter', SubmitType::class);;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vehicule::class,
        ]);
    }
}

src/Controller/VehiculeController.php
<?php

namespace App\Controller;

use App\Entity\Vehicule;
use App\Form\AgenceType;
use App\Form\VehiculeType;
use App\Repository\VehiculeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class VehiculeController extends AbstractController
{  
    /**
     * @Route("/admin/vehicule", name="app_vehicule")
     */
    public function index(VehiculeRepository $repoVehicule, Request $request, EntityManagerInterface $manager): Response
    {
        $vehicule = new Vehicule;
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);
        $vehicules = $repoVehicule->findAll();
        
        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($vehicule);
            $manager->flush();

            $this->addFlash('success', "le vehicule" . $vehicule->getId() ."a bien été ajoutée");

            return $this->redirectToRoute("app_vehicule");
        }

        return $this->render('vehicule/index.html.twig', [
            "vehicules" => $vehicules,
            "formVehicule" => $form->createView()
        ]);
    }

     /**
     * @Route("/admin/vehicule/update/{id}", name="update_vehicule")
     */
    public function update(Vehicule $vehicule, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(VehiculeType::class, $vehicule);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($vehicule);
            $manager->flush();
    
            $this->addFlash('success', "le vehicule" . $vehicule->getId() ."a bien été modifiée");

            return $this->redirectToRoute("app_vehicule");
        }

        return $this->render("vehicule/update_vehicule.html.twig", [
            "formVehicule" => $form->createView(),
            "vehicule" => $vehicule
        ]);
    }

    /**
     * @Route("/admin/vehicule/supprimer/{id}", name="delete_vehicule")
     */
    public function delete(Vehicule $vehicule, EntityManagerInterface $manager)
    {
        $manager->remove($vehicule);
        $manager->flush();

        $this->addFlash('success', "le vehicule" . $vehicule->getId() . "a bien été supprimer");
        return $this->redirectToRoute("app_vehicule");
    }

        /**
     * @Route("/admin/vehicule/detail/{id}", name="detail_vehicule")
     */
    public function detail(vehicule $vehicule, EntityManagerInterface $manager, VehiculeRepository $repoVehicule, $id)
    {
        $vehicule = $repoVehicule->find($id);

        return $this->render('vehicule/detail_vehicule.html.twig', [
            "vehicule" => $vehicule,
        ]);
        return $this->redirectToRoute("detail_vehicule");
    }
}

templates/vehicule/detail_vehicule.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ parent()}} Vehicule | Detail{% endblock %}

{% block body %}

<div class="row justify-content-end">
    <a class="btn btn-info p-2 col-md-3" href="{{ path('app_vehicule') }}">Retour</a>
</div>

<table class="table">
  <thead>
    <tr>
    <th scope="col">Vehicule</th>
      <th scope="col">Agence</th>
      <th scope="col">Titre</th>
      <th scope="col">Marque</th>
      <th scope="col">Modele</th>
      <th scope="col">Description</th>
      <th scope="col">Photo</th>
      <th scope="col">Prix</th>
     
    </tr>

  </thead>

  <tbody>

    <tr>
      <td>{{ vehicule.id }}</td>
      <td>{{ vehicule.idAgence.ville }}</td>
      <td>{{ vehicule.titre }}</td>
      <td>{{ vehicule.marque }}</td>
      <td>{{ vehicule.modele }}</td>
      <td>{{ vehicule.description }}</td>
      <td> 
      <img src="{{ vehicule.photo }}" alt="" width=150 height=100>
      </td>
      <td>{{ vehicule.prixJournalier }}</td>
   
    </tr>
  </tbody>
</table>


{% endblock %}

templates/vehicule/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Vehicule {% endblock %}

{% block body %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">Vehicule</th>
      <th scope="col">Agence</th>
      <th scope="col">Titre</th>
      <th scope="col">Marque</th>
      <th scope="col">Modele</th>
      <th scope="col">Description</th>
      <th scope="col">Photo</th>
      <th scope="col">Prix</th>
      <th scope="col">Actions</th>
    </tr>

  </thead>

  <tbody>
 
  {% for vehicule in vehicules %}
  {% if vehicule.idAgence %}
    <tr>
      <td>{{ vehicule.id }}</td>
      <td>{{ vehicule.idAgence.ville }}</td>
      <td>{{ vehicule.titre }}</td>
      <td>{{ vehicule.marque }}</td>
      <td>{{ vehicule.modele}}</td>
      <td>{{ vehicule.description }}</td>
      <td> 
      <img src="{{ vehicule.photo }}" alt="photoVehicule" width=150 height=100>
      </td>
      <td>{{ vehicule.prixJournalier }}</td>
      <td class="w-25">
      <a href="{{ path('update_vehicule', {'id' : vehicule.id} ) }}">
      <img src="{{ asset('images/update.png')}}" alt="modif" width=35></a>

       <a href="{{ path('detail_vehicule', {'id' : vehicule.id} ) }}">
      <img src="{{ asset('images/details.png')}}" alt="modif" width=35></a>

      <a href="{{ path('delete_vehicule', {'id' : vehicule.id} ) }}">
      <img src="{{ asset('images/delete.png')}}" alt="modif" width=35></a>
      </td> 
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>



  {{ form_start(formVehicule) }}
    <div class="col-md-10 mx-auto">
        {{ form_row(formVehicule) }}
    </div>
    

    {{ form_end(formVehicule) }}
{% endblock %}

templates/vehicule/update_vehicule.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ parent()}} Vehicule | Update{% endblock %}
{% block body %}

<div class="row justify-content-end">
    <a class="btn btn-info p-2 col-md-3" href="{{ path('app_vehicule') }}">Retour</a>
</div>

<div class="col_md-4 mx-auto">

{{ form_start(formVehicule) }}

    <div class="col-md-10 mx-auto">

{{ form_row(formVehicule) }}
    </div>

    {{ form_end(formVehicule) }}

</div>

{% endblock %}