src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
class Membre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 60)]
    private ?string $mdp = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column]
    private ?int $statut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    // public function __construct(){
    //     $this->date_enregistrement = new \DateTimeMutable();
    // }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(int $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pseudo', TextType::class, [
                "label" => "Pseudo",
                "required" => true,
                "attr" => [
                    "placeholder" => "pseudo",
                    "class" => "form-control"
                ]

            ])
            ->add('mdp', PasswordType::class, [
                "label" => "Mot de passe",
                "required" => true,
                "attr" => [
                    "placeholder" => "mot de passe",
                    "class" => "form-control"
                ]
            ])
            ->add('nom', TextType::class, [
                "label" => "Nom",
                "required" => true,
                "attr" => [
                    "placeholder" => "nom",
                    "class" => "form-control"
                ]
            ])
            ->add('prenom', TextType::class, [
                "label" => "Prénom",
                "required" => true,
                "attr" => [
                    "placeholder" => "prenom",
                    "class" => "form-control"
                ]
            ])
            ->add('email', EmailType::class, [
                "label" => "Email",
                "required" => true,
                "attr" => [
                    "placeholder" => "email",
                    "class" => "form-control"
                ]
            ])
            ->add('civilite', ChoiceType::class, [
                "label" => "Civilite",
                "required" => true,
                'choices'  => [
                    'Homme' => "homme",
                    'Femme' => "femme",
                    
                ]
                
            ])
            ->add('statut', ChoiceType::class, [
                "label" => "Statut",
                "required" => true,
                'choices'  => [
                    'user' => "0",
                    'admin' => "1",
                ]
            
                
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Repository\MembreRepository;
use App\Form\MembreType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class MembreController extends AbstractController
{

    #[Route('/admin/membre', name: 'membre_afficher')]
    public function afficher_ajouter_membre(MembreRepository $repoMembre, Request $request, EntityManagerInterface $manager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $objet_membre = new Membre;
        $membres = $repoMembre->findAll();
        

        $form = $this->createForm(MembreType::class, $objet_membre);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            
            // $hashedPassword = $passwordHasher->hashPassword(
            //     $objet_membre,
            //     $request->get("membre")["mdp"]
            // );
        
            // $objet_membre->setPassword($hashedPassword);
            // $repoMembre->save($objet_membre, true);
            $objet_membre->setDateEnregistrement(new \DateTime());
            $manager->persist($objet_membre);
            $manager->flush();

            $this->addFlash("Success", "Le membre N° " . $objet_membre->getId() . "a bien été ajouté");
        }

        return $this->render('membre/membre_afficher.html.twig', [
            'controller_name' => 'MembreController',
            "formMembre" => $form->createView(),
            "membres" => $membres,
        ]);
        return $this->redirectToRoute("membre_afficher");

    }

    /**
    * @Route("/admin/membre/update/{id}", name="membre_update")
    */
    public function update(Membre $membre, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($membre);
            $manager->flush();

            $this->addFlash('success', "l'agence N" . $membre->getId() ."a bien été modifiée");

            return $this->redirectToRoute("membre_afficher");
        }

        return $this->render("membre/membre_update.html.twig", [
            "formMembre" => $form->createView(),
            "membre" => $membre,
        ]);
    }

    /**
    * @Route("/admin/membre/delete/{id}", name="membre_delete")
    */
    public function membre_delete(Membre $membre, EntityManagerInterface $manager){

        $manager->remove($membre);
        $manager->flush();

        $this->addFlash("Success", "Le membre N°". $membre->getId() . " a bien été supprimé");
        return $this->redirectToRoute('membre_afficher');

    }

     /**
    * @Route("/admin/membre/details/{id}", name="membre_details")
    */
    public function membre_details(Membre $membre, EntityManagerInterface $manager, MembreRepository $repoMembre, $id){

        $membre = $repoMembre->find($id);

        return $this->render('membre/membre_details.html.twig', [
            'controller_name' => 'MembreController',
            "membre" => $membre,
        ]);
        return $this->redirectToRoute("membre_details");


    }







}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MembreController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/Symfony/VV/Veville_location/src/Controller/MembreController.php'|file_link(0) }}">src/Controller/MembreController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/Symfony/VV/Veville_location/templates/membre/index.html.twig'|file_link(0) }}">templates/membre/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/membre/membre_afficher.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent()}} Membres{% endblock %}

{% block body %}


<div class="container">
{% if membres %}
    <table class="table">
  <thead>
    <tr>

      <th scope="col">#id_membre</th>
      <th scope="col">Pseudo</th>
      <th scope="col">Nom</th>
      <th scope="col">Prénom</th>
      <th scope="col">Email</th>
      <th scope="col">Civilite</th>
      <th scope="col">Statut</th>
      <th scope="col">Date_enregistrement</th>
      <th scope="col">Actions</th>

    </tr>
  </thead>
  <tbody>
  {% for membre in membres %}
            <tr>
                <td>{{ membre.id }}</td>
                <td>{{ membre.pseudo }}</td>
                <td>{{ membre.nom }}</td>
                <td>{{ membre.prenom }}</td>
                <td>{{ membre.email }}</td>
                <td>{{ membre.civilite }}</td>
                <td>{{ membre.statut }}</td>
                <td>{{ membre.dateEnregistrement|date("Y-m-d H:i:s")}}</td>
            
                {# {{ path("category_modifier", {"id" : membre.id})}} #}

            <td>
                
            </td>

            <td>
                <a href="{{ path("membre_update", {"id" : membre.id})}}" >
                    <img src="{{ asset("images/update.png")}}" alt="icône de modification" style="width:2rem">
                </a>

                <a href="{{ path("membre_delete", {"id" : membre.id})}}" >
                    <img src="{{ asset("images/delete.png")}}" alt="icône de suppression" style="width:2rem">
                </a>

                <a href="{{ path("membre_details", {"id" : membre.id})}}" >
                    <img src="{{ asset("images/details.png")}}" alt="icône de suppression" style="width:2rem">
                </a>
            </td> 

            </tr>

            {% endfor %}
   
    
  </tbody>
</table>

{% endif %}

 {{ form_start(formMembre)}}

 <div class="col-md-10 mx-auto">
        {{ form_row(formMembre.pseudo) }}
    </div>
<div class="col-md-10 mx-auto">
        {{ form_row(formMembre.mdp) }}
    </div>

    <div class="col-md-10 mx-auto">
        {{ form_row(formMembre.nom) }}
    </div>

    <div class="col-md-10 mx-auto">
        {{ form_row(formMembre.prenom) }}
    </div>

    <div class="col-md-10 mx-auto">
        {{ form_row(formMembre.email) }}
    </div>

    <div class="col-md-10 mx-auto">
        {{ form_row(formMembre.civilite) }}
    </div>
    <div class="col-md-10 mx-auto">
        {{ form_row(formMembre.statut) }}
    </div>


    <div class="row justify-content-center">
        <input type="submit" class="btn btn-success mt-3 col-md-6" value="Ajouter">
    </div>
</div>

{{ form_end(formMembre)}}
   {% endblock %}

   

templates/membre/membre_details.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent()}} Membres | Details{% endblock %}

{% block body %}

<div class="container">

 <table class="table">
  <thead>
    <tr>

      <th scope="col">#id_membre</th>
      <th scope="col">Pseudo</th>
      <th scope="col">Nom</th>
      <th scope="col">Prénom</th>
      <th scope="col">Email</th>
      <th scope="col">Civilite</th>
      <th scope="col">Statut</th>
      <th scope="col">Date_enregistrement</th>
      <th scope="col">Actions</th>

    </tr>
  </thead>
  <tbody>
  
            <tr>
                <td>{{ membre.id }}</td>
                <td>{{ membre.pseudo }}</td>
                <td>{{ membre.nom }}</td>
                <td>{{ membre.prenom }}</td>
                <td>{{ membre.email }}</td>
                <td>{{ membre.civilite }}</td>
                <td>{{ membre.statut }}</td>
                {# <td>{{ membre.date_enregistrement}}</td> #}
                
                
                {# {{ path("category_modifier", {"id" : membre.id})}} #}


            <td>
                
            </td>

            <td>
                <a href="{{ path("membre_update", {"id" : membre.id})}}" >
                    <img src="{{ asset("images/update.png")}}" alt="icône de modification" style="width:2rem">
                </a>

                <a href="{{ path("membre_delete", {"id" : membre.id})}}" >
                    <img src="{{ asset("images/delete.png")}}" alt="icône de suppression" style="width:2rem">
                </a>

                <a href="{{ path("membre_details", {"id" : membre.id})}}" >
                    <img src="{{ asset("images/details.png")}}" alt="icône de suppression" style="width:2rem">
                </a>
            </td> 

            </tr>

           
   
    
  </tbody>
</table>
</div>


{% endblock %}

templates/membre/membre_update.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent()}} Membres Update{% endblock %}

{% block body %}

{{ form_start(formMembre)}}

{{ form_row(formMembre) }}

    <div class="row justify-content-center">
        <input type="submit" class="btn btn-success mt-3 col-md-6" value="Ajouter">
    </div>
</div>

{{ form_end(formMembre)}}





{% endblock %}